python -u run.py \
  --is_training 1 \
  --model iTransformer \
  --model_id traffic_96 \
  --data custom \
  --root_path ./data/traffic/ \
  --data_path traffic.csv \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --batch_size 8 \
  --e_layers 4 \
  --n_heads 4 \
  --d_model 512 \
  --d_ff 512 \
  --attn_bits 4 \
  --ffn_bits 4 \
  --itr 1 \
  --checkpoints ./checkpoints/traffic_box_96 \
  --teacher_path ./path/to/your/fp32_teacher_checkpoint.pth 